### ISSUE TITLE
remove accents / diacritics from usernames

### ISSUE THREAD

**Issue by klarasch** [eyp-developers/statistics#137]
some users may have problems logging in if the username contains characters that are not on their keyboard by default

**Comment by wolfskaempf** [comment]
Thank you @klarasch for the suggestion. Especially in international teams with lots of different keyboards this could improve the login experience.

**Comment by wolfskaempf** [comment]
This is now a feature! See Commit https://github.com/eyp-developers/statistics/commit/ea323172776e828b7ed61e631da9d21916592371 for the code changes and https://github.com/eyp-developers/statistics/commit/5499a91904cb7675ec6883a3fa07f3194e6f1f5c for the documentation changes.
