### ISSUE TITLE
create session form sometimes won't create a session

### ISSUE THREAD

**Issue by wolfskaempf** [eyp-developers/statistics#156]
I suspect it has something to do with the picture author link, which, if copied directly from Flickr is often longer than 200 characters which exceeds the maximum length for this field

**Comment by wolfskaempf** [comment]
It seems the length of the content of the URLFields is not the issue. Testing revealed it worked flawlessly with more than 1000 characters.

**Comment by ostenbom** [comment]
Think all this has to do with making users too soon, not cleaning up if errors and not returning anything helpful if form is not valid:
https://github.com/eyp-developers/statistics/issues/162
https://github.com/eyp-developers/statistics/issues/145
